package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class lj implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label(value = "age")
	private java.lang.Integer age;

	public lj() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public lj(java.lang.String name, java.lang.Integer age) {
		this.name = name;
		this.age = age;
	}

}