package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class lj implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public lj() {
    }




}